{"name": "test_div[int]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 1.0", "trace": "self = <test_calcutor.TestCalc object at 0x0000000003CE6CA0>\nget_instance = <pythoncode.Calculator.Calculator object at 0x0000000003CE68E0>\nget_datas_with_fixture = [1, 1, 2]\n\n    def test_div(self,get_instance, get_datas_with_fixture):\n    \n        f = get_datas_with_fixture\n    \n        try:\n>           assert f[2] == get_instance.div(f[0],f[1])\nE           assert 2 == 1.0\n\ntest_calcutor.py:77: AssertionError"}, "attachments": [{"name": "stdout", "source": "352459d0-1f49-4d04-9fac-e052185eeb9d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_with_fixture", "value": "[1, 1, 2]"}], "start": 1615198034564, "stop": 1615198034565, "uuid": "e57c68bb-950e-4c9c-b58a-c582bad580c6", "historyId": "9685d88096ade3fe3deba0be77b04cc4", "testCaseId": "42d6b15ebfef6dc8ff0705bb87b06251", "fullName": "test_calcutor.TestCalc#test_div", "labels": [{"name": "suite", "value": "test_calcutor"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "ZX-201601031503"}, {"name": "thread", "value": "2260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calcutor"}]}